# Claire Ruffing
# cmruffin
# Makefile for HW3 Making Some Moves

JAVASRC	   = ChessMoves.java Node.java LinkedList.java ChessPiece.java Rook.java Bishop.java Queen.java King.java Knight.java Pawn.java
SOURCES    = README Makefile $(JAVASRC)
MAINCLASS  = ChessMoves
CLASSES    = ChessMoves.class Node.class LinkedList.class ChessPiece.class Rook.class Bishop.class Queen.class King.class Knight.class Pawn.class
JARFILE    = ChessMoves.jar

all: $(JARFILE)

$(JARFILE): $(CLASSES)	
	echo Main-class: $(MAINCLASS) > Manifest 
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)

$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)	

clean:
	rm $(CLASSES) $(JARFILE)



