#
# CSE183 Assignment 8
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8
  version: 0.1.0
  title: CSE183 Assignment 8

servers:
  - url: http://localhost:3010

paths:
  /v0/mail:
    get:
      description: Returns all EMail
      parameters:
      - name: mailbox
        in: query
        required: false
        description: Mailbox name
        schema:
          type: string
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailbox'
        404:
          description: Unknown mailbox
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new email
      requestBody:
        description: Save a new email that was sent
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmail'
      responses:
        201:
          description: Application response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        400:
          description: Unexpected properties in submitted email
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v0/mail/{id}:
    get:
      description: Returns an email identified by the id
      parameters:
      - name: id
        in: path
        description: id of the identified email
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Email found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        404:
          description: Id does not identify a known email
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Returns an email identified by the id
      parameters:
      - in: query
        name: mailbox
        description: Mailbox name
        required: true
        schema:
          type: string
      - in: path
        name: id
        description: id of the identified email
        required: true
        schema:
          type: string
          format: uuid
      responses:
        204:
          description: Email found and updated
        404:
          description: Id does not identify a known email
        409:
          description: If mailbox is the sent one and mail identified by id is not in sent mailbox
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Mailbox:
      description: An array of mailboxes
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          mail:
            type: array
            items:
              $ref: '#/components/schemas/MailboxEmail'

    MailboxEmail:
      description: A mailbox full of emails
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        received:
          type: string
          format: date-time
        sent:
          type: string
          format: date-time
      required:
        - id
        - to
        - from
        - subject
        - received
        - sent

    Email:
      description: All properties of an email
      allOf:
      - $ref: '#/components/schemas/MailboxEmail'
      required:
        - content
      properties:
        content:
          type: string

    NewEmail:
      type: object
      properties:
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        content:
          type: string
      required:
        - to
        - subject
        - content

