# Claire Ruffing
# cmruffin
# Makefile for HW5 Hashtable

JAVASRC	   = Bard.java WordObj.java Sorter.java
SOURCES    = README Makefile $(JAVASRC)
MAINCLASS  = Bard
CLASSES    = Bard.class WordObj.class Sorter.class
JARFILE    = Bard.jar

all: $(JARFILE)

$(JARFILE): $(CLASSES)	
	echo Main-class: $(MAINCLASS) > Manifest 
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)

$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)	

clean:
	rm $(CLASSES) $(JARFILE)



