# Claire Ruffing
# cmruffin
# Makefile for HW2 Maintaining Your Chess Board

ChessBoard: ChessBoard.class	
	echo Main-class: ChessBoard > Manifest 
	jar cvfm ChessBoard.jar Manifest ChessBoard.class
	rm Manifest

ChessBoard.class: ChessBoard.java
	javac -Xlint ChessBoard.java

Node.class: Node.java
	javac -Xlint Node.java

LinkedList.class: LinkedList.java
	javac -Xlint LinkedList.java

ChessPiece.class: ChessPiece.java
	javac -Xlint ChessPiece.java

Rook.class: Rook.java
	javac -Xlint Rook.java

Bishop.class: Bishop.java
	javac -Xlint Bishop.java

Queen.class: Queen.java
	javac -Xlint Queen.java

King.class: King.java
	javac -Xlint King.java

Knight.class: Knight.java
	javac -Xlint Knight.java

Pawn.class: Pawn.java
	javac -Xlint Pawn.java

clean:
	rm -f ChessBoard.jar ChessBoard.class



